allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: true
  nx: true
  sharp: true
minimumReleaseAgeExclude:
  - '@img/sharp-darwin-arm64@0.35.3'
  - '@img/sharp-darwin-x64@0.35.3'
  - '@img/sharp-freebsd-wasm32@0.35.3'
  - '@img/sharp-linux-arm64@0.35.3'
  - '@img/sharp-linux-arm@0.35.3'
  - '@img/sharp-linux-ppc64@0.35.3'
  - '@img/sharp-linux-riscv64@0.35.3'
  - '@img/sharp-linux-s390x@0.35.3'
  - '@img/sharp-linux-x64@0.35.3'
  - '@img/sharp-linuxmusl-arm64@0.35.3'
  - '@img/sharp-linuxmusl-x64@0.35.3'
  - '@img/sharp-wasm32@0.35.3'
  - '@img/sharp-webcontainers-wasm32@0.35.3'
  - '@img/sharp-win32-arm64@0.35.3'
  - '@img/sharp-win32-ia32@0.35.3'
  - '@img/sharp-win32-x64@0.35.3'
  - astro@7.0.5
  - sharp@0.35.3
shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - sharp
